[package]
name = "wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
rand = "0.8"
k256 = {version = "0.13.4", features = ["ecdsa", "pkcs8"] }
blockchain = { path = "../blockchain" }